= Single Sign On with Arkane using Spring Boot


This guide will walk you through the process of logging in with Arkane using Single Sign On and displaying your Arkane wallets.
This specific guide will focus on Spring Boot integration.

=== What you'll build

We'll build a small application which will:

1. Allow us to authenticate using your Arkane Account (OAuth2)
2. Fetch and display your wallets, server side

== What you'll need

* A text editor or IDE
* Java 8+ and Maven must be installed

=== Creating a new project

```bash
mkdir ui && cd ui
$ curl https://start.spring.io/starter.tgz -d style=web -d name=simple | tar -xzvf -
```

=== Enabling Arkane Login

To be able to log in using Arkane, we'll have to add oauth2 support to our Spring Boot application.

```xml
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-oauth2</artifactId>
</dependency>
```

=== Adding Oauth2 Support

First of all, we'll need to enable oauth2 support.
Simply add `@EnableOAuth2Client` and autowire `OAuth2ClientContext` in a configuration class.

Next up, we'll create a new instance of AuthorizationCodeResourceDetails and provide it as a bean.

```java
@Bean
@ConfigurationProperties("arkane.client")
public AuthorizationCodeResourceDetails arkane() {
    return new AuthorizationCodeResourceDetails();
}
```

 We'll populate our application with properties from a property file.

```
arkaneBaseUrl=https://login-staging.arkane.network/auth/realms/Arkane
arkane.client.user-authorization-uri=${arkaneBaseUrl}/protocol/openid-connect/auth
arkane.client.client.scope=openid
arkane.client.access-token-uri=${arkaneBaseUrl}/protocol/openid-connect/token
arkane.client.tokenName=bearerToken
arkane.client.preEstablishedRedirectUri=http://localhost:4000/login/arkane
arkane.client.clientId=Arketype
```

On top of that we'll have to add the properties for the resource server.

```java
@Bean
@ConfigurationProperties("arkane.resource")
public ResourceServerProperties arkaneResource() {
    return new ResourceServerProperties();
}
```

```
arkane.resource.userInfoUri=${keycloakBaseUrl}/protocol/openid-connect/userinfo
```

Make one of your configuration classes extend from `WebSecurityConfigurerAdapter` and implement the configure method.

```java
@Override
protected void configure(HttpSecurity http) throws Exception {
    http.antMatcher("/**")
    .csrf().disable()
    .addFilterBefore(ssoFilter(), BasicAuthenticationFilter.class);
}
```

The last thing we'll need to do is create a filter, which we'll add to our web security configuration.

```java
private Filter ssoFilter() {
    OAuth2ClientAuthenticationProcessingFilter arkaneFilter = new OAuth2ClientAuthenticationProcessingFilter("/login/arkane");
    OAuth2RestTemplate facebookTemplate = arkaneTemplate();
    arkaneFilter.setRestTemplate(facebookTemplate);
    UserInfoTokenServices tokenServices = new UserInfoTokenServices(arkaneResource().getUserInfoUri(), arkane().getClientId());
    tokenServices.setRestTemplate(facebookTemplate);
    arkaneFilter.setTokenServices(tokenServices);
    return arkaneFilter;
}
```


== Run the application

Run your application. If you'll navigate to `/login/arkane`, you'll be redirected to Arkane to login. After logging in, you'll be fully authenticated in your application, using the Arkane Single Sign on.



