== Introduction

This guide will walk you trough the process of creating a multi blockchain wallet, able to transfer native coins and tokens to any address specified.  After this intro you will understand the different Arkane components and be able to integrate all features from link:reference.html[Reference documentation].

=== What you'll build

We'll build a page which will:

* Authenticate the user using the Arkane Connect authentication provider
* Fetch a list of the user's wallets
* Enable the user to manage his wallets connected to our application
* Fetch the token balances of the selected wallet
* Execute a transaction, from the selected wallet to a specified address

In this example, the following components will be used link:buildingblocks.html#_arkane_identity[[.bb-identity]#Arkane Identity#] link:buildingblocks.html#_arkane_api[[.bb-api]#Arkane API#] link:buildingblocks.html#_arkane_connect[[.bb-connect]#Arkane Connect#].

=== Prerequisities

* A text editor or IDE
* Git (https://git-scm.com/downloads[Download])
* Node & npm (https://www.npmjs.com/get-npm[Download])
* A minimal understanding of jQuery (we will be using jQuery to perform DOM manipulations)
* An understanding of async functions (ECMAScript 2017)

== Let’s get started

We'll start by setting up our development environment. Open a terminal window, checkout the https://github.com/ArkaneNetwork/js-example[sample project], called js-example, from GitHub, go to the `initial` branch and run `npm install`.
[source, bash]
----
git clone https://github.com/ArkaneNetwork/js-example.git
cd js-example
git checkout initial
npm install
----

This will set us up with a small project that contains the necessary HTML, CSS and configuration files. +
It will also setup an http server which you can start by executing `npm run start`. The server will be running on port 4000 (http://localhost:4000).

At the moment the application isn't doing much, so let's go ahead and implement the JavaScript.

== Arkane Connect link:connect-js.html[[.small]#+[More info]+#]

Before we can actually start writing the JavaScript, we need to add https://www.npmjs.com/package/@arkane-network/arkane-connect[Arkane Connect] as a dependency to our project. To do this, open up `package.json` and add `"@arkane-network/arkane-connect": "latest"` to the `dependencies` section.

./package.json
[source,json]
----
"dependencies": {
  "@arkane-network/arkane-connect": "latest", // <1>
  "jquery": "^3.3.1"
},
----
<.> The Arkane Connect dependency

After this is done, rerun `npm install`.
[source, bash]
----
npm install
----

Now we can add `connect.js` to our application by adding it in the `<head>` section of `/public/index.html`.

NOTE: If using Typescript, it can also be included as `import ArkaneConnect from '@arkane-network/arkane-connect;`.

./public/index.html
[source,html]
----
<head>
  ...
  <link rel="stylesheet" href="/assets/css/arketype.css"/>

  <script src="/node_modules/@arkane-network/arkane-connect/dist/connect.js"></script> <!--1-->
</head>
...
----
<.> Adding Arkane Connect to the HTML page

After adding it in our HTML, we can create an `ArkaneConnect` instance. In `./public/assets/js/main.js` add the following snippet:

./public/assets/js/main.js
[source,javascript]
----
var app = app || {};

app.initApp = () => {
  window.arkaneConnect = new ArkaneConnect('Arketype', { environment: 'staging'});
};

app.initApp();
----

By adding this snippet, we will create an ArkaneConnect instance that will connect to the Arkane staging environment (for production, you can just omit the `environment` property).


== Quick and easy
After finishing the steps above, the fastest and easiest way to get started will be using the `arkaneConnect.flows.getAccount` function.
This function starts a flow that will make sure the user logs in (if not already) and gives access to at least one wallet. More info on this flow, link:connect-js.html#get-account[+[Check getAccount()]+].
This quick start will go a bit more in depth, and gives a step by step guide how to manage the user and wallets. Starting with authentication in the next paragraph.

== Authenticating link:connect-js.html#_authentication[[.small]#+[More info]+#] link:buildingblocks.html#arkane-identity[[.small]#+[More on Arkane Identity]+#]

In this guide, we're going to use the authentication client baked into Arkane Connect. This client will authenticate against the Arkane Connect authentication provider and then store (and refresh when needed) the bearer token necessary for any call to Arkane.

=== Check if authenticated
The first thing we'll want to do is check if the user is already authenticated.

In the snippet below, you can see that the `checkAuthenticated()` function is called. This will check if the user is authenticated.

The outcome of calling this function is a Promise containing an authentication result, which contains two callback methods `+authenticated((auth) => { ... });+` and `+notAuthenticated((auth) => { ... });+`.

./public/assets/js/main.js
[source,javascript]
----
...
app.initApp = async () => {
    window.arkaneConnect = new ArkaneConnect('Arketype', {environment: 'staging'});
    try {
        const authenticationResult = await window.arkaneConnect.checkAuthenticated();
        app.afterAuthentication(authenticationResult);
    } catch (reason) {
        console.error(reason);
    }
};

app.afterAuthentication = (authenticationResult) => {
    authenticationResult
        .authenticated(async (auth) => {
            console.log('This user is authenticated', auth);
            document.body.classList.add('logged-in');
            $('#auth-username').text(auth.idTokenParsed.name);

            try {
                const wallets = await window.arkaneConnect.api.getWallets();
                if (wallets.length > 0) {
                    const walletsMap = app.convertArrayToMap(wallets, 'id');
                    localStorage.setItem('wallets', JSON.stringify(walletsMap));
                    app.populateWalletsSelect(wallets);
                } else {
                    window.arkaneConnect.manageWallets('ETHEREUM');
                }
            } catch (err) {
                console.error('Something went wrong while fetching the user\'s wallets');
            }
        })
        .notAuthenticated((auth) => {
            console.log('This user is not authenticated', auth);
        });
};

app.initApp();
----
<.> Added `async` to the function to be able to use `await`
<.> Checking if the user is authenticated
<.> Handeling the user is authenticated
<.> Handeling the user is not authenticated

=== Handling authentication outcome
Let's make the authentication outcome determine if the user sees a 'Login'-link or the wallet application.


We'll extend the authenticated handler so that it adds the `logged-in` class to the `<body>` element of our page. This will let the CSS in `/public/assets/css/auth.css` handle the displaying and hiding of the correct section.

./public/assets/js/main.js
[source,javascript]
----
...
try {
  const authenticationResult = await window.arkaneConnect.checkAuthenticated();
  authenticationResult.authenticated((auth) => {
    console.log("This user is authenticated", auth);
    document.body.classList.add('logged-in'); // <1>
    $('#auth-username').text(auth.idTokenParsed.name); // <2>
  })
  .notAuthenticated((auth) => {
    console.log("This user is not authenticated", auth);
  });
}
...
----
<.> Adding the `logged-in` class
<.> Displaying the logged in user's name

=== Login / Logout

Next we'll want to allow the user to authenticate when he clicks the login-link and log out when he calls the logout-link.

We'll do this by adding 'click' event listeners to the bottom of our script. These will handle a click by calling the `arkaneConnect.flows.authenticate()` or `arkaneConnect.logout()` respectively.

./public/assets/js/main.js
[source,javascript]
----
...
app.initApp();

$('#auth-loginlink').click(async (event) => {
    event.preventDefault();
    authenticationResult = await window.arkaneConnect.flows.authenticate(); // <1>
    app.afterAuthentication(authenticationResult);
});

$('#auth-logout').click((event) => {
  event.preventDefault();
  window.arkaneConnect.logout(); // <2>
});
----
<.> Authenticate the user
<.> Log the user out

That's it, we've now integrated the authentication client of Arkane Connect. It checks if we're authenticated and displays a login- / logout-link when appropriate. If you want to see it in action go ahead and run `npm run start` and surf to http://localhost:4000.

[source, bash]
----
npm run start
----

== Wallets link:connect-js.html#wallet-api[[.small]#+[More info]+#]
=== Fetch wallets

We can fetch the user's wallets using the Arkane Connect API which can be accessed by calling `arkaneConnect.api`. This API is a JavaScript proxy to the HTTP endpoints exposed on https://api.arkane.network[]. By using the Arkane Connect API, you don't have to construct and execute the HTTP calls yourself.

For this example we'll extend the `authenticated(...)` handler so that it fetches the user's wallets right after he logs in, convert the array to a map (where the key is `id`), store the map in local storage and populate the wallets `<select>` with them.

./public/assets/js/main.js
[source,javascript]
----
...
try {
  const authenticationResult = await window.arkaneConnect.checkAuthenticated();

  authenticationResult.authenticated(async (auth) => { // <1>
    console.log("This user is authenticated", auth);
    document.body.classList.add('logged-in');
    $('#auth-username').text(auth.idTokenParsed.name);

    try {
        const wallets = await window.arkaneConnect.api.getWallets(); // <2>
        const walletsMap = app.convertArrayToMap(wallets, 'id'); // <3>
        localStorage.setItem('wallets', JSON.stringify(walletsMap)); // <4>
        app.populateWalletsSelect(wallets); <5>
    }
    catch (err) {
        console.error('Something went wrong while fetching the user\'s wallets');
    }
  })
  .notAuthenticated((auth) => {
    console.log("This user is not authenticated", auth);
  });
}
...

// Below the app.initApp(...) function //
...
app.convertArrayToMap = (array, key) => {
  return array.reduce((obj, item) => {
    obj[item[key]] = item;
    return obj;
  }, {});
};

app.populateWalletsSelect = (wallets) => {
  const walletsSelect = $('#wallets-select');
  wallets.forEach((wallet) => {
    walletsSelect.append($('<option>', { value : wallet.id }).text(`${wallet.secretType} - ${wallet.address}`));
  });
};
...
----
<.> Added `async` to the function to be able to use `await`
<.> Fetch the wallets using the Arkane Connect API
<.> Convert the array of wallets to a map with 'id' as key
<.> Store the map of wallets in local storage
<.> Populate the wallets `<select>`

=== Manage Wallets
The first time a user enters our sample application, he will need to give our our application access to at least one of his wallets. To do this we will launch Arkane Connect’s `Manage wallets` page. +
This page displays all the user’s wallets for a specified blockchain and allows him to give our application access to one or more. Additionally he has the ability to create a new, or import an existing wallet.

To redirect the user to the `Manage wallets` page, we need to call `arkaneConnect.flows.manageWallets(<blockchain>)`. Let’s do this right after we’ve gotten the user’s wallets. If no wallets are returned, we’ll redirect the user to the manage wallets page (for Ethereum wallets).

./public/assets/js/main.js
[source,javascript]
----
...
try {
  const wallets = await window.arkaneConnect.api.getWallets();
  if (wallets.length > 0) { <1>
    const walletsMap = app.convertArrayToMap(wallets, 'id');
    localStorage.setItem('wallets', JSON.stringify(walletsMap));
    app.populateWalletsSelect(wallets);
  } else {
    window.arkaneConnect.flows.manageWallets('ETHEREUM'); <2>
  }
}
...
----
<.> Check if the user already has wallets linked to our application
<.> If no wallets are linked, redirect the user to the `Manage wallets` page (for Ethereum)

We'll also want `Manage wallets` links so that the user can go to the page without being automatically redirected somehow. To do this, we'll add 'click' event listeners to the links already on the page, which will redirect the user to the `Manage wallets` page for the correct blockchain.

./public/assets/js/main.js
[source,javascript]
----
// At the bottom of the file //
...
$('#manage-eth-wallets').click((event) => {
  event.preventDefault();
  window.arkaneConnect.flows.manageWallets('ETHEREUM'); <1>
});

$('#manage-vechain-wallets').click((event) => {
  event.preventDefault();
  window.arkaneConnect.flows.manageWallets('VECHAIN'); <2>
});
----
<.> Manage Ethereum wallets
<.> Manage VeChain wallets

=== Show wallet details
When the user selects a wallet we would like to show some details.

First, we're going to populate and show `wallet-balance` and `wallet-gas-balance` when the `<select>` value changes, by adding a 'change' event listener on `wallets-select`

./public/assets/js/main.js
[source,javascript]
----
// At the bottom of the file //
...

$('#wallets-select').change((event) => {
  event.preventDefault();
  if(event.target.value) {
    const wallets = JSON.parse(localStorage.getItem('wallets')); // <1>
    const wallet = wallets[event.target.value]; // <1>
    const balance = wallet.balance; // <1>
    $('#wallet-address').html(wallet.address); // <2>
    $('#wallet-balance').html(`${balance.balance} ${balance.symbol}`); // <3>
    $('#wallet-gas-balance').html(`${balance.gasBalance} ${balance.gasSymbol}`); // <4>
    $('#selected-wallet').removeClass('hidden'); // <5>
  }
  else {
    $('#selected-wallet').addClass('hidden'); // <6>
  }
});
----
<.> Fetching the wallet (+ balance) from localStorage
<.> Displaying the wallet address
<.> Displaying the tokens balance
<.> Displaying the gas balance
<.> Show the selected wallet
<.> Hide the selected wallet when none selected

Next we would like to show the tokens that are available for this wallet, we  can do this by extending the 'change' event listener with  `arkaneConnect.api.getTokenBalances(walletId)`, which will fetch the token balances.

./public/assets/js/main.js
[source,javascript,options="nowrap"]
----
$('#wallets-select').change(async (event) => { // <1>
  event.preventDefault();
  if (event.target.value) {
    const wallets = JSON.parse(localStorage.getItem('wallets'));
    const wallet = wallets[event.target.value];
    $('#wallet-address').html(wallet.address);
    $('#wallet-balance').html(`${wallet.balance.balance} ${wallet.balance.symbol}`);
    $('#wallet-gas-balance').html(`${wallet.balance.gasBalance} ${wallet.balance.gasSymbol}`);

    const tokenBalances = await window.arkaneConnect.api.getTokenBalances(wallet.id); // <2>
    $('#wallet-tokens').html(tokenBalances.map(
      (tokenBalance) => `${tokenBalance.balance} ${tokenBalance.symbol}`).join('<br/>') // <3>
    );

    $('#selected-wallet').removeClass('hidden');
  }
  else {
    $('#selected-wallet').addClass('hidden');
  }
});
----
<.> Making the callback function `async` so that we can use `await`
<.> Fetching the tokens balance for our wallet
<.> Displaying the tokens balance

NOTE: Reference documentation: link:reference.html#wallet[Wallet]

== [[transactions]]Transactions link:connect-js.html#transactions[[.small]#+[More info]+#]
=== Show form
The main feature of our multi-chain wallet is the transaction functionality. In `/public/index.html` there is already a form present. We're going to extend `wallets-select` 'change' event listener so that it pre-fills the walletId and populates a `<select>` to select the token the user wants to transfer.

./public/assets/js/main.js
[source,javascript]
----
...
  $('#wallet-tokens').html(
    tokenBalances.map((tokenBalance) => `${tokenBalance.balance} ${tokenBalance.symbol}`).join('<br/>')
  );

  $('#secret-type').val(wallet.secretType); // <1>
  app.preFillTransactionTokens(wallet, tokenBalances); <2>

  $('#selected-wallet').removeClass('hidden');
}
...
----
<.> Pre-filling the secretType (AKA the type of blockchain)
<.> Pre-filling the tokens

To make it work, we'll also need to add the code of the `app.preFillTransactionTokens(...)` function.

./public/assets/js/main.js
[source,javascript]
----
// At the bottom of the file //
...
app.preFillTransactionTokens = (wallet, tokenBalances) => {
    const transactionTokens = $('#transaction-token');
    transactionTokens.empty();
    transactionTokens.append($('<option>', {value: ''}).text(wallet.balance.symbol));
    tokenBalances.forEach((tokenBalance) => {
        transactionTokens.append(
            $('<option>', {value: tokenBalance.tokenAddress}).text(tokenBalance.symbol)
        );
    });
};
----

=== Execute transaction
To wrap things up, we'll want to execute a transaction. Using Arkane Connect, this is done by creating a new `Signer` via `arkaneConnect.createSigner()` and then calling its `signer.executeTransaction(genericTransactionRequest)` function.

We'll implement this by adding a `submit` event listener on the form to process the transaction.

IMPORTANT: If you're executing a transaction in an event handler (as in the example below), create the signer at the very beginning of your listener function. Otherwise the popup blocker of the browser might block the signer popup.

./public/assets/js/main.js
[source,javascript]
----
// At the bottom of the file //
...

$('#transaction-form').submit(async (event) => {
  event.preventDefault();
  const signer = window.arkaneConnect.createSigner(); // <1>

  try {
    const transactionResult = await signer.executeTransaction( // <2>
      {
        walletId: $("#transaction-form select[name='from']").val(), // <3>
        to: $("#transaction-form input[name='to']").val(), // <3>
        value: ($("#transaction-form input[name='amount']").val()), // <3>
        secretType: $("#transaction-form input[name='secretType']").val(), // <3>
        tokenAddress: $("#transaction-form select[name='tokenAddress']").val(), // <3>
      }
    );
    console.log(transactionResult.result.transactionHash);  // <4>
  }
  catch (reason) {
    console.error(reason);
  }
});
----
<.> Creating the signer instance (+ opening the popup)
<.> Execute the transaction
<.> Passing the form data
<.> Logging the transactionHash to the console

== Summary
Congratulations! You've just built a fully functional multi-chain wallet.

Here's an overview of what we've covered:

* We integrated the Arkane Connect authentication client
* We fetched a user's Arkane wallets
* We enabled the user to manage the wallets connected to our application
* We fetched a wallet's tokens balance
* We enabled the user to execute a transaction from one of his wallets

In this example, the following components were used link:buildingblocks.html#_arkane_identity[[.bb-identity]#Arkane Identity#] link:buildingblocks.html#_arkane_api[[.bb-api]#Arkane API#] link:buildingblocks.html#_arkane_connect[[.bb-connect]#Arkane Connect#].

The sample code used during this guide can either be https://github.com/ArkaneNetwork/js-example/archive/master.zip[downloaded] or https://github.com/ArkaneNetwork/js-example[explored] on GitHub.

== What's next
Now that you've mastered the basics you can dive deeper in the different building blocks or link:reference.html[explore] all our functionalities to enhance the sample app into your own personal wallet.
