== Building blocks

=== ARKANE API

The Arkane API is the core application of Arkane Network. It's a restful API, which consists of various endpoints to:

- View a user's wallets
- Request the balance or token balance of any Arkane Wallet
- Get the profile of a user
- Create signatures using an Arkane Wallet.


==== WHAT

==== Calling the Arkane API
To call an Arkane API, all you need is an endpoint and a valid authentication. 

WARNING: The Arkane API can also be used with API keys instead of Bearer Tokens. Using this authentication method is only encouraged in small scripts.

==== Result Wrapping

All of the API's responses are wrapped in an envelope. This envelope indicates whether the request succeeded. If the request failed, an additional `errors` object is added to the response.

*Example of a successful response*
[source,json]
----
{
  "success" : true,
  "result" : {
    "userId" : "davy",
    "hasMasterPin" : true
  }
}
----

*Example of a failed response*

[source,json]
----
{
    "success": false,
    "errors": [
        {
            "code": "pincode.no-tries-left",
            "message": "Max pincode tries exceeded"
        }
    ]
}
----

==== Authentication




=== ARKANE CONNECT

==== WHAT

Arkane Connect is an endpoint specifically designed to perform common tasks with Arkane wallets. Connect was created as a way to perform tasks which are

. otherwise not possible due to security reasons, like creating signatures
. necessary by all applications, like linking wallets your client

Basically, Arkane Connect is a small web application without a central entry point. Calls to Arkane Connect are made by navigating to a specific url. Although you can use it by itself - by manually crafting the urls - we also provide a javascript SDK.  

==== HOW    
 
. data
. url
. bearerToken
. redirectUrl

NOTE: Make sure all query parameters are url encoded (ex. https://www.urlencoder.org/)