= Arkane for native apps

This documentation applies to:

- A native mobile application (IOS / Android / ...)
- A native desktop app

== Quickstart

If you want an example on how to build a simple wallet using Arkane, you can follow the quickstart. There you will build a native Android app with wallet functionality based on Arkane.

include::../reference/buildingblocks.adoc[]

== Reference documentation

=== Wallet

This section describes all actions related to wallets.

==== Link [.bb-connect]#connect#

This allows users to link his existing wallets with your application. The difference with <<Manage wallets>>:

* A user can only link wallets, it is not possible to create or import a wallet
* A list of all wallets is returned for any chain (it is possible to filter this).

An example use case could be a portfolio app where a user wants to quickly link all his wallets to get an overview of his complete portfolio.


To link wallets, use the connect building block with:

.URL
https://connect-staging.arkane.network/wallets/link

.Data
_No data needed_


==== Manage wallets [.bb-connect]#connect#


As an application, it is possible to have a user manage his wallets for a specific chain. During this action, the user can link existing wallets or import a wallet.
When the user returns to the app, a wallet will be linked to your application for the given chain. When a user does not have any wallets yet, a user can indicate to create a new wallet.

To manage wallets, a specific url needs to be opened in the browser (using custom tabs). It is not possible to do this directly in the background since the user needs to enter his PIN. For security reasons, we cannot allow it to be entered inside your own app.

To manage wallets, use the connect building block with:

.URL
https://connect-staging.arkane.network/wallets/manage

.Data parameters
|===
|Name |Description |Example

|chain
|The chain for which you want to manage wallets.
|ethereum

|===


.Data example
[source,json]
----
{
  "chain": "ethereum"
}
----

==== List user wallets [.bb-api]#api#
operation::get-wallets[snippets='curl-request,http-response,response-fields']

It's also possible to filter based on secret type

operation::get-wallets-filtered[snippets='request-parameters']


==== Get specific user wallet

=== Balance

==== Native balance

==== Token balances

==== Specific token balance

=== Transactions

==== Transfer

==== Native Transactions

===== Ethereum
===== Vechain

=== Profile
==== User profile
