== Wallet

This section describes all actions related to wallets.

=== [[link-wallets]] Link wallets link:buildingblocks.html#_arkane_connect[[.bb-connect]#Arkane Connect#]

This allows users to link his existing wallets with your application. The difference with <<manage-wallets, Manage wallets>>:

- A user can only link wallets, it is not possible to create or import a wallet
- A list of all wallets is returned for any chain (it is possible to filter this).

An example use case could be a portfolio app where a user wants to quickly link all his wallets to get an overview of his complete portfolio.


To link wallets, use the connect building block with:

.URL
https://connect-staging.arkane.network/wallets/link

.Data
_No data needed_

=== [[manage-wallets]] Manage wallets link:buildingblocks.html#_arkane_connect[[.bb-connect]#Arkane Connect#]

As an application, it is possible to have a user manage his wallets for a specific chain. During this action, the user can link existing wallets or import a wallet.
When the user returns to the app, a wallet will be linked to your application for the given chain. When a user does not have any wallets yet, a user can indicate to create a new wallet.

To manage wallets, use the connect building block with:

.URL
https://connect-staging.arkane.network/wallets/manage


.Data parameters
|===
|Name |Description |Example
|chain
|The chain for which you want to manage wallets.
|ethereum
|===


.Data example
[source,json]
----
{
  "chain": "ethereum"
}
----

=== [[list-wallets]] List wallets link:buildingblocks.html#_arkane_api[[.bb-api]#Arkane API#]
Returns all the wallets for the specified user (bearer token)

operation::get-wallets[snippets='curl-request,http-response,response-fields']

It's also possible to filter based on secret type

operation::get-wallets-filtered[snippets='request-parameters']


[[get-specific-user-wallet]]
=== [[get-wallet]] Get wallet link:buildingblocks.html#_arkane_api[[.bb-api]#Arkane API#]
Returns the details for a specific wallet (native balance is also included)

operation::get-wallet[snippets='curl-request,path-parameters,http-response,response-fields']

=== [[get-balance]] Native balance link:buildingblocks.html#_arkane_api[[.bb-api]#Arkane API#]
Returns the "native" balance for a wallet. This is the balance of the native token used by the chain. Ex. ETH for Ethereum.

operation::get-balance[snippets='curl-request,path-parameters,http-response,response-fields']

=== [[get-token-balances]] Token balances link:buildingblocks.html#_arkane_api[[.bb-api]#Arkane API#]
Returns the balance of all tokens currently supported by Arkane. The list of supported tokens can be found on https://github.com/ArkaneNetwork/content-management/tree/master/tokens[Github].

operation::get-token-balances[snippets='curl-request,request-fields,http-response,response-fields']

=== [[get-token-balance]] Specific token balance link:buildingblocks.html#_arkane_api[[.bb-api]#Arkane API#]
Returns the token balance for a specified token (this can be any token).

operation::get-token-balance[snippets='curl-request,path-parameters,http-response,response-fields']

== Transactions

[[transfer]]
=== Transfer link:buildingblocks.html#_arkane_connect[[.bb-connect]#Arkane Connect#]
This can be used to transfer (native) tokens from a wallet to another wallet. To start a transfer you need to:

.URL
https://connect-staging.arkane.network/transaction/execute


.[[generic-transaction-request]] Data parameters
operation::build-transaction-request[snippets='request-fields']

.Data example
operation::build-transaction-request[snippets='request-body']

.Result parameters
|===
|Path|Type|Description

|`+transactionHash+`
|`+String+`
|The transaction hash

|===

.Result example
[source,json]
----
{
  "transactionHash" : "0x621f692e386a8bc0c53d36aa793864893106e10f54f63fa9c063e24ad975d907"
}
----

[NOTE]
====
If you want to perform a token transfer, add the field "tokenAddress". For "native" transfers, simply omit the field "tokenAddress".
====

[IMPORTANT]
====
For the *value*, we expect the *"decimal value"*. If a token has 18 decimals and you want to transfer 1 of the specific token, provide the value 1. Arkane will translate this to the correct non decimal value being: 1 * 10e18.
Using this, you don't have to take the different number of decimals for different tokens into account.
====

[[native-transactions]]

=== Ethereum
==== Execute ETH transaction link:buildingblocks.html#_arkane_connect[[.bb-connect]#Arkane Connect#]
To execute an Ethereum transaction, use the connect building block with:

.URL
https://connect-staging.arkane.network/transaction/execute/eth_transaction


.Data parameters
operation::execute-ether-transaction[snippets='request-fields']

.Data example
operation::execute-ether-transaction[snippets='request-body']

.Result parameters
operation::execute-ether-transaction[snippets='response-fields']

.Result example
operation::execute-ether-transaction[snippets='response-body']

==== Execute ERC20 transfer link:buildingblocks.html#_arkane_connect[[.bb-connect]#Arkane Connect#]

To execute an ERC20 transaction transfer, use the connect building block with:

.URL
https://connect-staging.arkane.network/transaction/execute/ethereum_erc20_transaction


.Data parameters
operation::execute-erc20-transaction[snippets='request-fields']

.Data example
operation::execute-erc20-transaction[snippets='request-body']

.Result parameters
operation::execute-erc20-transaction[snippets='response-fields']

.Result example
operation::execute-erc20-transaction[snippets='response-body']

==== Sign link:buildingblocks.html#_arkane_connect[[.bb-connect]#Arkane Connect#]
Signs arbitrary data. This data is before UTF-8 HEX decoded and enveloped as followed:

`"\x19Ethereum Signed Message:\n" + message.length + message.`

To sign data, use the connect building block with:

.URL
https://connect-staging.arkane.network/transaction/sign/ethereum_raw

.Data parameters
operation::sign-hex-message[snippets='request-fields']

.Data example
operation::sign-hex-message[snippets='request-body']

.Result parameters
operation::sign-hex-message[snippets='response-fields']

.Result example
operation::sign-hex-message[snippets='response-body']


=== Gochain
==== Execute GO transaction link:buildingblocks.html#_arkane_connect[[.bb-connect]#Arkane Connect#]
To execute an Gochain transaction, use the connect building block with:

.URL
https://connect-staging.arkane.network/transaction/execute/go_transaction


.Data parameters
operation::execute-go-transaction[snippets='request-fields']

.Data example
operation::execute-go-transaction[snippets='request-body']

.Result parameters
operation::execute-go-transaction[snippets='response-fields']

.Result example
operation::execute-go-transaction[snippets='response-body']

==== Execute GO20 transfer link:buildingblocks.html#_arkane_connect[[.bb-connect]#Arkane Connect#]

To execute an GO20 transaction transfer, use the connect building block with:

.URL
https://connect-staging.arkane.network/transaction/execute/ethereum_go20_transaction


.Data parameters
operation::execute-go20-transaction[snippets='request-fields']

.Data example
operation::execute-go20-transaction[snippets='request-body']

.Result parameters
operation::execute-go20-transaction[snippets='response-fields']

.Result example
operation::execute-go20-transaction[snippets='response-body']

==== Sign link:buildingblocks.html#_arkane_connect[[.bb-connect]#Arkane Connect#]
Signs arbitrary data. This data is before UTF-8 HEX decoded and enveloped as followed:

`"\x19Ethereum Signed Message:\n" + message.length + message.`

To sign data, use the connect building block with:

.URL
https://connect-staging.arkane.network/transaction/sign/gochain_raw

.Data parameters
operation::sign-hex-message[snippets='request-fields']

.Data example
operation::sign-hex-message[snippets='request-body']

.Result parameters
operation::sign-hex-message[snippets='response-fields']

.Result example
operation::sign-hex-message[snippets='response-body']

=== Vechain

==== [[execute-vet-transaction]] Execute VET transaction link:buildingblocks.html#_arkane_connect[[.bb-connect]#Arkane Connect#]
To execute an VeChain transaction, use the connect building block with:

.URL
https://connect-staging.arkane.network/transaction/execute/vet_transaction


.Data parameters
operation::execute-vet-transaction[snippets='request-fields']

.Data example
operation::execute-vet-transaction[snippets='request-body']

.Result parameters
operation::execute-vet-transaction[snippets='response-fields']

.Result example
operation::execute-vet-transaction[snippets='response-body']

==== Execute VTHO transfer link:buildingblocks.html#_arkane_connect[[.bb-connect]#Arkane Connect#]
To execute a VTHO transfer, use the connect building block with:

.URL
https://connect-staging.arkane.network/transaction/execute/vtho_transaction

.Data parameters
operation::execute-vtho-transaction[snippets='request-fields']

.Data example
operation::execute-vtho-transaction[snippets='request-body']

.Result parameters
operation::execute-vtho-transaction[snippets='response-fields']

.Result example
operation::execute-vtho-transaction[snippets='response-body']

.Result parameters
|===
|Path|Type|Description

|`+transactionHash+`
|`+String+`
|The transaction hash

|===

.Result example

[source,json]
----
{
  "transactionHash" : "0x621f692e386a8bc0c53d36aa793864893106e10f54f63fa9c063e24ad975d907"
}
----

==== Execute VIP180 transfer link:buildingblocks.html#_arkane_connect[[.bb-connect]#Arkane Connect#]

To execute an ERC20 transaction transfer, use the connect building block with:

.URL
https://connect-staging.arkane.network/transaction/execute/ethereum_erc20_transaction


.Data parameters
operation::execute-vechain-erc20-transaction[snippets='request-fields']

.Data example
operation::execute-vechain-erc20-transaction[snippets='request-body']

.Result parameters
operation::execute-vechain-erc20-transaction[snippets='response-fields']

.Result example
operation::execute-vechain-erc20-transaction[snippets='response-body']

=== Bitcoin

==== [[execute-bitcoin-transaction]] Execute Bitcoin transaction link:buildingblocks.html#_arkane_connect[[.bb-connect]#Arkane Connect#]
To execute an Bitcoin transaction, use the connect building block with:

.URL
https://connect-staging.arkane.network/transaction/execute/btc_transaction


.Data parameters
operation::execute-btc-transaction[snippets='request-fields']

.Data example
operation::execute-btc-transaction[snippets='request-body']

.Result parameters
operation::execute-btc-transaction[snippets='response-fields']

.Result example
operation::execute-btc-transaction[snippets='response-body']

=== Litecoin

==== [[execute-litecoin-transaction]] Execute Bitcoin transaction link:buildingblocks.html#_arkane_connect[[.bb-connect]#Arkane Connect#]
To execute an Litecoin transaction, use the connect building block with:

.URL
https://connect-staging.arkane.network/transaction/execute/ltc_transaction


.Data parameters
operation::execute-ltc-transaction[snippets='request-fields']

.Data example
operation::execute-ltc-transaction[snippets='request-body']

.Result parameters
operation::execute-ltc-transaction[snippets='response-fields']

.Result example
operation::execute-ltc-transaction[snippets='response-body']

== Profile
=== [[user-profile]] User profile link:buildingblocks.html#_arkane_api[[.bb-api]#Arkane API#]
Returns more info about the connected user.

operation::get-profile[snippets='http-request,http-response,response-fields']


== Swap
This section describes how to use the swapping functionality within Arkane. It allows you to swap/exchange a (native) token to (native) token.

=== [[swap-get-trading-pairs]] Trading pairs link:buildingblocks.html#_arkane_api[[.bb-api]#Arkane API#]
Returns the list of possible trading pairs for a given wallet.

operation::swap-tradingpairs-vechain[snippets='curl-request,path-parameters,http-response,response-fields']

=== [[swap-get-exchange-rate]] Exchange rate link:buildingblocks.html#_arkane_api[[.bb-api]#Arkane API#]
Returns the exchange rate for a specified swap.

operation::swap-exchangerate-vechain[snippets='curl-request,request-parameters,http-response,response-fields']

=== [[swap-get-exchange-rate]] Create swap link:buildingblocks.html#_arkane_api[[.bb-api]#Arkane API#]
Creates the transaction request that is needed to execute the swap. With this result (the transaction request), you will need to call the native transactions
endpoint to execute the swap. Ex. for VeChain, use the output from this call to the input of: <<execute-vet-transaction, Execute VET transaction>>

operation::swap-vechain[snippets='curl-request,path-parameters,http-response,response-fields']