== Wallet

This section describes all actions related to wallets.

=== [[create-wallet]] Create wallet link:buildingblocks.html#_arkane_api[[.bb-api]#Arkane API#]
Create a whitelabel wallet

operation::create-whitelabel-wallet[snippets='curl-request,http-response,response-fields'&pincode=true]

=== [[list-wallets]] List wallets link:buildingblocks.html#_arkane_api[[.bb-api]#Arkane API#]
Returns all the wallets for the client

operation::get-wallets[snippets='curl-request,http-response,response-fields'&pincode=true]

It's also possible to filter based on secret type

operation::get-wallets-filtered[snippets='request-parameters'&pincode=true]


[[get-specific-user-wallet]]
=== [[get-wallet]] Get wallet link:buildingblocks.html#_arkane_api[[.bb-api]#Arkane API#]
Returns the details for a specific wallet (native balance is also included)

operation::get-wallet[snippets='curl-request,path-parameters,http-response,response-fields'&pincode=true]

=== [[get-balance]] Native balance link:buildingblocks.html#_arkane_api[[.bb-api]#Arkane API#]
Returns the "native" balance for a wallet. This is the balance of the native token used by the chain. Ex. ETH for Ethereum.

operation::get-balance[snippets='curl-request,path-parameters,http-response,response-fields'&pincode=true]

=== [[get-token-balances]] Token balances link:buildingblocks.html#_arkane_api[[.bb-api]#Arkane API#]
Returns the balance of all tokens currently supported by Arkane. The list of supported tokens can be found on https://github.com/ArkaneNetwork/content-management/tree/master/tokens[Github].

operation::get-token-balances[snippets='curl-request,http-response,response-fields'&pincode=true]

=== [[get-token-balance]] Specific token balance link:buildingblocks.html#_arkane_api[[.bb-api]#Arkane API#]
Returns the token balance for a specified token (this can be any token).

operation::get-token-balance[snippets='curl-request,path-parameters,http-response,response-fields'&pincode=true]

=== [[nft-get-for-address]] List Non Fungible Tokens (NFT's) link:buildingblocks.html#_arkane_api[[.bb-api]#Arkane API#]

[WARNING]
====
Currently this functionallity is only supported for Ethereum wallets (ERC-721), other chains will follow
====

Returns the list of NFT's owned by a wallet

operation::list-non-fungibles[snippets='curl-request,path-parameters,request-parameters,http-response,response-fields'&pincode=true]

=== [[wallet-error-codes]] Error codes

|===
|Error Code | Meaning

|wallet.archived
|The wallet that is used appears to be archived

|wallet.forbidden
|Wallet to update was not found or does not belong to the correct user

|wallet.balance.not.supported.yet
|Getting the balance for chain is not supported yet

|wallet.encrypt.internal-error
|Problem while trying to encrypt user secret

|wallet.decrypt.internal-error
|A problem occurred while trying to access your wallet. Please contact support

|wallet.secret.not-found
|The specified secret was not found in our vault

|wallet.secret.internal-error
|An unknown error occurred when trying to fetch the secret. Please contact support.
|===

== [[transactions]] Transactions

[[transfer]]
=== Transfer link:buildingblocks.html#_arkane_connect[[.bb-connect]#Arkane Connect#]
This can be used to transfer (native) tokens from a wallet to another wallet. To start a transfer you need to:

.[[generic-transaction-request]] Data parameters
operation::build-generic-transfer-request[snippets='request-fields'&pincode=true]

[IMPORTANT]
====
[[build-value]] ^[1]^ As *value*, we expect the "*decimal value*". If a token has 18 decimals and you want to transfer 1 token, provide the value 1. Arkane will translate this to the correct non decimal value (1 * 10e18).
Using this, you don't have to take into account the number of decimals for different tokens.
====

[NOTE]
====
[[build-token-address]] ^[2]^ If you want to perform a *token transfer*, add the field `tokenAddress`. For native transfers, simply omit it.
====

[NOTE]
====
[[build-network]] ^[3]^ (Only for Ethereum) The node to which the transaction will be send can be set manually. This can be done using the `network` parameter. +
This feature enables you to submit a transaction to any mainnet node of your choosing, a testnet node (e.g. Kovan, Rinkeby, …​) or a different (private) network altogether.
====

.Data example
operation::build-generic-transfer-request[snippets='curl-request'&pincode=true]

.Result parameters
|===
|Path|Type|Description

|`+transactionHash+`
|`+String+`
|The transaction hash

|===

.Result example
[source,json]
----
{
  "transactionHash" : "0x621f692e386a8bc0c53d36aa793864893106e10f54f63fa9c063e24ad975d907"
}
----

[[native-transactions]]

=== Ethereum

==== [[execute-eth-transaction]] Execute ETH transaction link:buildingblocks.html#_arkane_connect[[.bb-connect]#Arkane Connect#]
To execute an Ethereum transaction, use the connect building block with:

.Data parameters
operation::execute-ether-transaction[snippets='request-fields'&pincode=true]

[NOTE]
====
[[eth-network]] ^[1]^ The node to which the transaction will be send can be set manually. This can be done using the `network` parameter. +
This feature enables you to submit a transaction to any mainnet node of your choosing, a testnet node (e.g. Kovan, Rinkeby, …​) or a different (private) network altogether.
====

.Data example
operation::execute-ether-transaction[snippets='curl-request'&pincode=true]

.Result parameters
operation::execute-ether-transaction[snippets='response-fields'&pincode=true]

.Result example
operation::execute-ether-transaction[snippets='response-body'&pincode=true]

==== Execute ERC20 transfer link:buildingblocks.html#_arkane_connect[[.bb-connect]#Arkane Connect#]

To execute an ERC20 transaction transfer, use the connect building block with:

.Data parameters
operation::execute-erc20-transaction[snippets='request-fields'&pincode=true]

[NOTE]
====
[[erc20-network]] ^[1]^ The node to which the transaction will be send can be set manually. This can be done using the `network` parameter. +
This feature enables you to submit a transaction to any mainnet node of your choosing, a testnet node (e.g. Kovan, Rinkeby, …​) or a different (private) network altogether.
====

.Data example
operation::execute-erc20-transaction[snippets='curl-request'&pincode=true]

.Result parameters
operation::execute-erc20-transaction[snippets='response-fields'&pincode=true]

.Result example
operation::execute-erc20-transaction[snippets='response-body'&pincode=true]

==== Execute ERC721 transfer link:buildingblocks.html#_arkane_connect[[.bb-connect]#Arkane Connect#]

To execute an ERC721 transaction transfer, use the connect building block with:

.Data parameters
operation::execute-erc721-transaction[snippets='request-fields'&pincode=true]

[NOTE]
====
[[erc721-network]] ^[1]^ The node to which the transaction will be send can be set manually. This can be done using the `network` parameter. +
This feature enables you to submit a transaction to any mainnet node of your choosing, a testnet node (e.g. Kovan, Rinkeby, …​) or a different (private) network altogether.
====

.Data example
operation::execute-erc721-transaction[snippets='curl-request'&pincode=true]

.Result parameters
operation::execute-erc721-transaction[snippets='response-fields'&pincode=true]

.Result example
operation::execute-erc721-transaction[snippets='response-body'&pincode=true]


==== Sign link:buildingblocks.html#_arkane_connect[[.bb-connect]#Arkane Connect#]
Signs arbitrary data. This data is before UTF-8 HEX decoded and enveloped as followed:

`"\x19Ethereum Signed Message:\n" + message.length + message.`

To sign data, use the connect building block with:

.Data parameters
operation::sign-hex-message[snippets='request-fields'&pincode=true]

.Data example
operation::sign-hex-message[snippets='curl-request'&pincode=true]

.Result parameters
operation::sign-hex-message[snippets='response-fields'&pincode=true]

.Result example
operation::sign-hex-message[snippets='response-body'&pincode=true]

==== Error Codes

|===
|Error Code | Meaning

|transaction.submit.ethereum-error
|Something went wrong while trying to submit the ethereum transaction

|web3.internal-error
|Something went wrong with the underlying web3 connection.

|web3.estimate.gas.internal-error
|A problem occurred trying to estimate the gas.

|web3.nonce.internal-error
|A problem occurred trying to get the next nonce

|web3.transaction.submit.internal-error
|A problem occurred trying to submit the transaction to the Ethereum network
|===

=== Gochain

==== Execute GO transaction link:buildingblocks.html#_arkane_connect[[.bb-connect]#Arkane Connect#]
To execute an Gochain transaction, use the connect building block with:

.Data parameters
operation::execute-go-transaction[snippets='request-fields'&pincode=true]

.Data example
operation::execute-go-transaction[snippets='curl-request'&pincode=true]

.Result parameters
operation::execute-go-transaction[snippets='response-fields'&pincode=true]

.Result example
operation::execute-go-transaction[snippets='response-body'&pincode=true]

==== Execute GO20 transfer link:buildingblocks.html#_arkane_connect[[.bb-connect]#Arkane Connect#]

To execute an GO20 transaction transfer, use the connect building block with:

.Data parameters
operation::execute-go20-transaction[snippets='request-fields'&pincode=true]

.Data example
operation::execute-go20-transaction[snippets='curl-request'&pincode=true]

.Result parameters
operation::execute-go20-transaction[snippets='response-fields'&pincode=true]

.Result example
operation::execute-go20-transaction[snippets='response-body'&pincode=true]

==== Sign link:buildingblocks.html#_arkane_connect[[.bb-connect]#Arkane Connect#]
Signs arbitrary data. This data is before UTF-8 HEX decoded and enveloped as followed:

`"\x19Ethereum Signed Message:\n" + message.length + message.`

To sign data, use the connect building block with:

.Data parameters
operation::sign-hex-message[snippets='request-fields'&pincode=true]

.Data example
operation::sign-hex-message[snippets='curl-request'&pincode=true]

.Result parameters
operation::sign-hex-message[snippets='response-fields'&pincode=true]

.Result example
operation::sign-hex-message[snippets='response-body'&pincode=true]

==== Error Codes

|===
|Error Code | Meaning

|transaction.submit.gochain-error
|Something went wrong while trying to submit the Gochain transaction
|===

=== Vechain

==== [[execute-vet-transaction]] Execute VET transaction link:buildingblocks.html#_arkane_connect[[.bb-connect]#Arkane Connect#]
To execute an VeChain transaction, use the connect building block with:

.Data parameters
operation::execute-vet-transaction[snippets='request-fields'&pincode=true]

.Data example
operation::execute-vet-transaction[snippets='curl-request'&pincode=true]

.Result parameters
operation::execute-vet-transaction[snippets='response-fields'&pincode=true]

.Result example
operation::execute-vet-transaction[snippets='response-body'&pincode=true]

==== Execute VTHO transfer link:buildingblocks.html#_arkane_connect[[.bb-connect]#Arkane Connect#]
To execute a VTHO transfer, use the connect building block with:

.Data parameters
operation::execute-vtho-transaction[snippets='request-fields'&pincode=true]

.Data example
operation::execute-vtho-transaction[snippets='curl-request'&pincode=true]

.Result parameters
operation::execute-vtho-transaction[snippets='response-fields'&pincode=true]

.Result example
operation::execute-vtho-transaction[snippets='response-body'&pincode=true]

.Result parameters
|===
|Path|Type|Description

|`+transactionHash+`
|`+String+`
|The transaction hash

|===

.Result example

[source,json]
----
{
  "transactionHash" : "0x621f692e386a8bc0c53d36aa793864893106e10f54f63fa9c063e24ad975d907"
}
----

==== Execute VIP180 transfer link:buildingblocks.html#_arkane_connect[[.bb-connect]#Arkane Connect#]

To execute an VIP180 transaction transfer, use the connect building block with:

.Data parameters
operation::execute-vechain-erc20-transaction[snippets='request-fields'&pincode=true]

.Data example
operation::execute-vechain-erc20-transaction[snippets='curl-request'&pincode=true]

.Result parameters
operation::execute-vechain-erc20-transaction[snippets='response-fields'&pincode=true]

.Result example
operation::execute-vechain-erc20-transaction[snippets='response-body'&pincode=true]

==== Error Codes

|===
|Error Code | Meaning

|thorify.internal-error
|Something went wrong with the underlying vechain connection

|thorify.transaction.submit.internal-error
|A problem occurred trying to submit the transaction to the vechain network
|===

=== Bitcoin

==== [[execute-bitcoin-transaction]] Execute Bitcoin transaction link:buildingblocks.html#_arkane_connect[[.bb-connect]#Arkane Connect#]
To execute an Bitcoin transaction, use the connect building block with:

.Data parameters
operation::execute-btc-transaction[snippets='request-fields'&pincode=true]

.Data example
operation::execute-btc-transaction[snippets='curl-request'&pincode=true]

.Result parameters
operation::execute-btc-transaction[snippets='response-fields'&pincode=true]

.Result example
operation::execute-btc-transaction[snippets='response-body'&pincode=true]

==== Error Codes

|Error Code | Meaning
|===
|bitcoin.address-wrong-network
|Something went wrong with the address of this bitcoin wallet on this specific network.

|bitcoin.creation-error
|An error occurred trying to create the Bitcoin transaction.

|bitcoin.transaction-inputs
|The account you're trying to use as origin in the transaction doesn't have valid inputs to send

|bitcoin.not-enough-funds
|Not enough funds to create the transaction

|bitcoin.signing-error
|An error occurred trying to sign the bitcoin transaction.
|===

=== Litecoin

==== [[execute-litecoin-transaction]] Execute Litecoin transaction link:buildingblocks.html#_arkane_connect[[.bb-connect]#Arkane Connect#]
To execute an Litecoin transaction, use the connect building block with:

.Data parameters
operation::execute-ltc-transaction[snippets='request-fields'&pincode=true]

.Data example
operation::execute-ltc-transaction[snippets='curl-request'&pincode=true]

.Result parameters
operation::execute-ltc-transaction[snippets='response-fields'&pincode=true]

.Result example
operation::execute-ltc-transaction[snippets='response-body'&pincode=true]

==== Error Codes

|===
|Error Code | Meaning

|litecoin.address-wrong-network
|Something went wrong with the address of this litecoin wallet on this specific network.

|litecoin.creation-error
|An error occurred trying to create the Litecoin transaction.

|litecoin.transaction-inputs
|The account you're trying to use as origin in the transaction doesn't have valid inputs to send

|litecoin.not-enough-funds
|Not enough funds to create the transaction

|litecoin.signing-error
|An error occurred trying to sign the litecoin transaction
|===

=== Tron

==== [[execute-trx-transaction]] Execute a TRON transaction link:buildingblocks.html#_arkane_connect[[.bb-connect]#Arkane Connect#]
To execute an TRON transaction, use the connect building block with:

.Data parameters
operation::execute-trx-transaction[snippets='request-fields'&pincode=true]

.Data example
operation::execute-trx-transaction[snippets='curl-request'&pincode=true]

.Result parameters
operation::execute-trx-transaction[snippets='response-fields'&pincode=true]

.Result example
operation::execute-trx-transaction[snippets='response-body'&pincode=true]


==== Execute TRC10 transfer link:buildingblocks.html#_arkane_connect[[.bb-connect]#Arkane Connect#]

To execute a TRC10 transaction transfer, use the connect building block with:

.Data parameters
operation::execute-trc10-transaction[snippets='request-fields'&pincode=true]

.Data example
operation::execute-trc10-transaction[snippets='curl-request'&pincode=true]

.Result parameters
operation::execute-trc10-transaction[snippets='response-fields'&pincode=true]

.Result example
operation::execute-trc10-transaction[snippets='response-body'&pincode=true]

==== Sign Raw Data link:buildingblocks.html#_arkane_connect[[.bb-connect]#Arkane Connect#]
Signs arbitrary data. .

To sign data, use the connect building block with:

.Data parameters
operation::sign-tron-hex-message[snippets='curl-request'&pincode=true]

.Data example
operation::sign-tron-hex-message[snippets='curl-request'&pincode=true]

.Result parameters
operation::sign-tron-hex-message[snippets='response-fields'&pincode=true]

.Result example
operation::sign-tron-hex-message[snippets='response-body'&pincode=true]

==== Error Codes

|===
|Error Code | Meaning

|tron.balance.bandwidth-error
|Unable to fetch bandwidth

|tron.signature.error
|An error occurred trying to create a tron signature
|===

=== Aeternity

==== [[execute-aeternity-transaction]] Execute AEternity transaction link:buildingblocks.html#_arkane_connect[[.bb-connect]#Arkane Connect#]
To execute an AEternity transaction, use the connect building block with:

.Data parameters
operation::execute-ae-transaction[snippets='request-fields'&pincode=true]

.Data example
operation::execute-ae-transaction[snippets='curl-request'&pincode=true]

.Result parameters
operation::execute-ae-transaction[snippets='response-fields'&pincode=true]

.Result example
operation::execute-ae-transaction[snippets='response-body'&pincode=true]

=== Neo

==== [[execute-neo-native-transaction]] Execute NEO Native transaction link:buildingblocks.html#_arkane_connect[[.bb-connect]#Arkane Connect#]
To execute an Neo Native transaction, use the connect building block with:

.Data parameters
operation::execute-neo-native-transaction[snippets='request-fields'&pincode=true]

.Data example
operation::execute-neo-native-transaction[snippets='curl-request'&pincode=true]

.Result parameters
operation::execute-neo-native-transaction[snippets='response-fields'&pincode=true]

.Result example
operation::execute-neo-native-transaction[snippets='response-body'&pincode=true]

==== [[execute-neo-gas-transaction]] Execute NEO Gas transaction link:buildingblocks.html#_arkane_connect[[.bb-connect]#Arkane Connect#]
To execute an Neo Gas transaction, use the connect building block with:


.Data parameters
operation::execute-neo-gas-transaction[snippets='request-fields'&pincode=true]

.Data example
operation::execute-neo-gas-transaction[snippets='curl-request'&pincode=true]

.Result parameters
operation::execute-neo-gas-transaction[snippets='response-fields'&pincode=true]

.Result example
operation::execute-neo-gas-transaction[snippets='response-body'&pincode=true]

==== [[sign-neo-message]] Sign Raw NEO Message link:buildingblocks.html#_arkane_connect[[.bb-connect]#Arkane Connect#]
To sign a raw neo transaction, use the connect building block with:

.Data parameters
operation::sign-neo-message[snippets='request-fields'&pincode=true]

.Data example
operation::sign-neo-message[snippets='curl-request'&pincode=true]

.Result parameters
operation::sign-neo-message[snippets='response-fields'&pincode=true]

.Result example
operation::sign-neo-message[snippets='response-body'&pincode=true]

=== [[transaction-error-codes]] Transaction Error Codes

|===
|Error Code | Meaning

|transaction.sign.internal-error
|A problem occurred trying to submit the sign the request

|transaction.insufficient-funds
|The account that initiated the transfer does not have enough energy

|transaction.sign.gas-error
|Unable to fetch default gas prices

|transaction.submit.internal-error
|A problem occurred trying to submit the sign the request

|transaction.submit.not-supported-yet
|Submitting a request to this network is not possible yet
|===

== Swap
This section describes how to use the swapping functionality within Arkane. It allows you to swap/exchange a (native) token to (native) token.

=== [[swap-get-trading-pairs]] Trading pairs link:buildingblocks.html#_arkane_api[[.bb-api]#Arkane API#]
Returns the list of possible trading pairs for a given wallet.

operation::swap-tradingpairs[snippets='curl-request,path-parameters,http-response,response-fields'&pincode=true]

=== [[swap-get-exchange-rate]] Exchange rate link:buildingblocks.html#_arkane_api[[.bb-api]#Arkane API#]
Returns the exchange rates for a specified swap.

operation::swap-exchangerate[snippets='curl-request,request-parameters,http-response,response-fields'&pincode=true]

=== [[swap-get-exchange-rate]] Create swap link:buildingblocks.html#_arkane_api[[.bb-api]#Arkane API#]
Creates the transaction requests that are needed to execute the swap. With this result (the transaction requests), you will need to call the native transactions
endpoint to execute the swap. Ex. for VeChain, use the output from this call to the input of: <<execute-vet-transaction, Execute VET transaction>>

operation::swap[snippets='curl-request,path-parameters,http-response,response-fields'&pincode=true]

=== [[swap-error-codes]] Swap Error Tokens

|===
|Error Code | Meaning

|swap.no-exchange-found
|No SwapService found for SwapExchange

|swap.uniswap.get-price.failed
|Unable to get the price of a token on uniswap

|swap.uniswap.allowance-error
|Unable to get allowance for token on uniswap

|swap.uniswap.exchange-not-found
|An exchange contract for a token on uniswap could not be found
|===